CON-2213 OpenFOAM 5.X import

diff --git a/wmake/scripts/AllwmakeParseArguments b/wmake/scripts/AllwmakeParseArguments
--- a/wmake/scripts/AllwmakeParseArguments
+++ b/wmake/scripts/AllwmakeParseArguments
@@ -2,7 +2,7 @@
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 2014-2016 OpenFOAM Foundation
+#   \\  /    A nd           | Copyright (C) 2014-2017 OpenFOAM Foundation
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
 # License
@@ -28,17 +28,20 @@
 #     Allwmake argument parser
 #
 # Usage
-#     # Declare the targetType and set to default for library building
-#     targetType=libso      # lib, libo or libso
-#
-#     # Declare genDoc and set to default if documentation building is supported
-#     genDoc=0              # 0 or 1
-#
 #     # Parse the arguments by sourcing this script
 #     . $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
 #
 #------------------------------------------------------------------------------
 Script=${0##*/}
+
+if [ -z "$WM_PROJECT_DIR" ]
+then
+    echo "$Script error: The OpenFOAM environment is not set."
+    echo "    Check the OpenFOAM entries in your dot-files and source them."
+    echo "    If in doubt, please read:"
+    echo "       http://openfoam.org/download/source/setting-environment"
+    exit 1
+fi
 
 usage() {
     exec 1>&2
@@ -49,47 +52,13 @@ usage() {
 
 Usage: $Script [OPTIONS]
 
-options:
-  -h or -help       Print list of Allwmake options
-  -k or -non-stop   Compile without stopping when errors occur
-  -j                Compile using all local cores/hyperthreads
-  -jN or -j N       Compile using N cores/hyperthreads
-  -no-scheduler     Compile without wmakeScheduler
-  -update           Update lnInclude directories, dep files, remove deprecated
-                    files and directories
+Executing $Script is equivalent to
+
+   wmake -all [OPTIONS]
 USAGE
 
-    # Print options for building code documentation
-    test -n "$genDoc" && cat<<USAGE_DOC
-  doc               Compile code documentation (requires Doxygen)
-USAGE_DOC
-
-    # Print options for building libraries
-    test -n "$targetType" && cat<<USAGE_LIB
-  lib               Compile statically linked archive lib (.a)
-  libo              Compile statically linked lib (.o)
-  libso             Compile dynamically linked lib (.so)
-  dep               Compile dependency files
-USAGE_LIB
-
+    wmake -help
     exit 1
-}
-
-
-#------------------------------------------------------------------------------
-# Set WM_NCOMPPROCS to number of cores on local machine
-#------------------------------------------------------------------------------
-
-setWM_NCOMPPROCS()
-{
-    if [ -r /proc/cpuinfo ]
-    then
-        WM_NCOMPPROCS=$(egrep "^processor" /proc/cpuinfo | wc -l)
-    else
-        WM_NCOMPPROCS=1
-    fi
-
-    export WM_NCOMPPROCS
 }
 
 
@@ -97,68 +66,51 @@ setWM_NCOMPPROCS()
 # Parse the arguments and options
 #------------------------------------------------------------------------------
 
-while [ "$#" -gt 0 ]
+fromWmake=
+qOpt=
+
+for arg in "$@"
 do
-    case "$1" in
-        # Print help
+    # Remove arg
+    shift
+
+    case "$arg" in
         -h | -help)
             usage
+            exit 0
             ;;
-        # Parallel compilation on all cores of local machine
-        -j)
-            setWM_NCOMPPROCS
-            test $# -ge 2 && expr $2 + 1 > /dev/null 2>&1 \
-                && shift && export WM_NCOMPPROCS=$1
-            echo "Compiling enabled on $WM_NCOMPPROCS cores"
+        # Check if called from wmake to avoid recusion
+        -fromWmake)
+            fromWmake="fromWmake"
             ;;
-        # Parallel compilation on specified number of cores
-        -j*)
-            export WM_NCOMPPROCS=${1#-j}
-            echo "Compiling enabled on $WM_NCOMPPROCS cores"
+        -q)
+            qOpt="-q"
+            # Permanently remove arg
+            continue
             ;;
-        # Non-stop compilation, ignoring errors
-        -k | -non-stop)
-            export WM_CONTINUE_ON_ERROR=1
-            ;;
-        # Disable scheduled parallel compilation
-        -no-scheduler)
-            unset WM_SCHEDULER
-            ;;
-        # Meant to be used following a pull, this will:
-        # - remove dep files that depend on deleted files;
-        # - remove stale dep files;
-        # - update lnInclude directories;
-        # - remove empty directories, along with deprecated object directories
-        #   and respective binaries.
-        -update)
-            wrmdep -update
-            wrmdep -old
-            wmakeLnIncludeAll
-            wclean empty
-
-            # Set WM_UPDATE_DEPENDENCIES, so that wmake will pick up on it
-            export WM_UPDATE_DEPENDENCIES=yes
-            ;;
-        # Generate documentation
-        doc)
-            test -n "$genDoc" || usage "invalid option '$1'"
-            genDoc=1
-            ;;
-        # Specify target type
-        lib | libo | libso | dep)
-            test -n "$targetType" || usage "invalid option '$1'"
-            targetType=$1
-            ;;
-        --)
-            shift
-            break
-            ;;
-        -* | *)
-            usage "invalid option '$1'"
+        # Target type
+        lib | libo | libso | dep | objects)
+            targetType=$arg
             ;;
     esac
-    shift
+
+    # Re-insert arg
+    set -- "$@" "$arg"
 done
+
+
+#------------------------------------------------------------------------------
+# Execute wmake -all if not called from wmake
+#------------------------------------------------------------------------------
+
+if [ -z "$fromWmake" ]
+then
+    exec wmake -all $qOpt $*
+else
+    # Print command
+    [ -z "$targetType" ] || targetSpace=" "
+    echo "$Script $targetType$targetSpace$(echo $PWD | sed s%$WM_PROJECT_DIR/%% )"
+fi
 
 
 #------------------------------------------------------------------------------
@@ -175,7 +127,7 @@ fi
 # Cleanup local variables and functions
 #------------------------------------------------------------------------------
 
-unset Script usage setWM_NCOMPPROCS
+unset Script usage fromWmake
 
 
 #------------------------------------------------------------------------------
diff --git a/wmake/scripts/wmakeFunctions b/wmake/scripts/wmakeFunctions
--- a/wmake/scripts/wmakeFunctions
+++ b/wmake/scripts/wmakeFunctions
@@ -35,7 +35,7 @@
 
 checkEnv()
 {
-    for envar in WM_OPTIONS WM_DIR WM_PROJECT_DIR
+    for envar in WM_OPTIONS WM_LINK_LANGUAGE WM_DIR WM_PROJECT_DIR
     do
         eval test "\$$envar" || {
             echo "$Script error: environment variable \$$envar not set" 1>&2
@@ -79,6 +79,32 @@ findTarget()
     fi
 }
 
+cdSource()
+{
+    if [ ! -d $MakeDir ]
+    then
+        echo "$Script: '$MakeDir' directory does not exist in $PWD" 1>&2
+        echo "    Searching up directories tree for Make directory"
+
+        findTarget .
+        targetType=
+
+        if [ "$dir" ]
+        then
+            cd $dir 2>/dev/null || {
+                echo "$Script error: could not change to directory '$dir'" 1>&2
+                exit 1
+            }
+        fi
+    fi
+
+
+    [ -r $MakeDir/files ] || {
+        echo "$Script error: file '$MakeDir/files' does not exist in $PWD" 1>&2
+        exit 1
+    }
+}
+
 findObjectDir()
 {
     expandPath $WM_PROJECT_DIR
@@ -102,12 +128,25 @@ findObjectDir()
     fi
 }
 
-depToSource()
-{
-    sourceFile=$(echo ${depFile%.dep} | \
-        sed -e s%platforms/${WM_OPTIONS}/%% -e s%Make/${WM_OPTIONS}/%% \
-            -e s%platforms/${WM_OPTIONS}${WM_MPLIB}/%% \
-            -e s%Make/${WM_OPTIONS}${WM_MPLIB}/%% )
-}
+if [ -n "$BASH_VERSION" ]; then
+    depToSource()
+    {
+        sourceFile=${depFile%.dep}
+        sourceFile="${sourceFile/platforms\/${WM_OPTIONS}\//}"
+        sourceFile="${sourceFile/Make\/${WM_OPTIONS}\//}"
+        sourceFile="${sourceFile/platforms\/${WM_OPTIONS}${WM_MPLIB}\//}"
+        sourceFile="${sourceFile/Make\/${WM_OPTIONS}${WM_MPLIB}\//}"
+    }
+else
+    depToSource()
+    {
+        sourceFile=$(echo ${depFile%.dep} |                 \
+            sed -e s%platforms/${WM_OPTIONS}/%%             \
+                -e s%Make/${WM_OPTIONS}/%%                  \
+                -e s%platforms/${WM_OPTIONS}${WM_MPLIB}/%%  \
+                -e s%Make/${WM_OPTIONS}${WM_MPLIB}/%% )
+    }
+fi
+
 
 #------------------------------------------------------------------------------
